#! /usr/bin/env bash

# also, to facilitate deployment to s3 on push, add a shell script to
# .git/hooks/pre-push containing:
# ./deploy-to-s3

echo "Deploy to S3..."
dotclean.js .
aws s3 sync --profile "bretton.wade@gmail.com" . s3://aws-website-bedrock-olhow --delete --include "*" --exclude ".*" --exclude "deploy-to-s3"
